import { TIME_WIDTH_ATTRS } from '@/assets/constants'

export const searchConditionColumns = [
  { label: '字段', prop: 'field', type: 'select', dict: 'fa_trans_query_col' },
  { label: '逻辑', prop: 'condition', type: 'select', dict: 'fa_trans_query_rule_nostr' },
  { label: '值', prop: 'value', type: 'input' },
] as any[]

export const intelligentTableColumns = [
  { label: '文件名称', prop: 'fileName', width: 120, showOverflowTooltip: true },
  { label: '行号', prop: 'rowNum', width: 80, align: 'center' },
  { label: '机构名称', prop: 'orgName', width: 140, showOverflowTooltip: true },
  { label: '客户号', prop: 'showCustomerCd', width: 120, showOverflowTooltip: true },
  { label: '客户名称', prop: 'customerName', width: 140, showOverflowTooltip: true },
  { label: '交易账号', prop: 'transAccountNo', width: 140, showOverflowTooltip: true },
  { label: '相关账号', prop: 'relAccountNo', width: 140, showOverflowTooltip: true },
  { label: '户名', prop: 'accountName', width: 120, showOverflowTooltip: true },
  { label: '币种', prop: 'currNo', width: 90, align: 'center' },
  { label: '交易状态', prop: 'status', width: 100, align: 'center' },
  { label: '交易方向', prop: 'transWay', width: 100, align: 'center' },
  { label: '交易金额', prop: 'transAmt', width: 120, align: 'right' },
  { label: '交易种类', prop: 'transType', width: 110, align: 'center' },
  { label: '业务日期', prop: 'bizDate', ...TIME_WIDTH_ATTRS },
  { label: '交易时间', prop: 'transTime', ...TIME_WIDTH_ATTRS },
  { label: '余额', prop: 'balence', width: 120, align: 'right' },
  { label: '对方机构名称', prop: 'counterOrgName', width: 160, showOverflowTooltip: true },
  { label: '对方账号', prop: 'counterAccountNo', width: 160, showOverflowTooltip: true },
  { label: '对方户名', prop: 'counterName', width: 160, showOverflowTooltip: true },
]

export const bankCustomerColumns = [
  { label: '文件', prop: 'fileName', width: 100 },
  { label: '行号', prop: 'rowNum', width: 80, align: 'center' },
  { label: '银行名称', prop: 'orgName', width: 120 },
  { label: '客户号', prop: 'showCustomerId', width: 120 },
  { label: '客户种类', prop: 'customerType', width: 100 },
  { label: '客户名称', prop: 'customerName', width: 140 },
  { label: '营业执照', prop: 'licenseNum', width: 140 },
  { label: '法人姓名', prop: 'legalPersonName', width: 120 },
  { label: '客户证件种类', prop: 'idType', width: 120 },
  { label: '客户证件号码', prop: 'idNum', width: 140 },
  { label: '手机号码', prop: 'teleNum', width: 120 },
  { label: '工作单位', prop: 'workUnit', width: 120 },
  { label: '账号', prop: 'accountNum', width: 140 },
  { label: '卡号', prop: 'cardNum', width: 140 },
  { label: '币种', prop: 'currNo', width: 90 },
  { label: '余额', prop: 'balence', width: 120, align: 'right' },
  { label: '账户类型', prop: 'accountType', width: 120 },
  { label: '备注', prop: 'comment', width: 140, showOverflowTooltip: true },
]

export const bankTransactionColumns = [
  { label: '文件', prop: 'fileName', width: 100 },
  { label: '行号', prop: 'rowNum', width: 80, align: 'center' },
  { label: '机构名称', prop: 'orgName', width: 120 },
  { label: '户名', prop: 'accountName', width: 120 },
  { label: '账号', prop: 'accountNum', width: 140 },
  { label: '卡号', prop: 'cardNum', width: 140 },
  { label: '流水号', prop: 'transNo', width: 120 },
  { label: '交易渠道', prop: 'channel', width: 100 },
  { label: '币种', prop: 'currNo', width: 90 },
  { label: '交易方向', prop: 'transWay', width: 100 },
  { label: '交易金额', prop: 'transAmt', width: 120, align: 'right' },
  { label: '贷方发生额', prop: 'creditAmt', width: 120, align: 'right' },
  { label: '余额', prop: 'balence', width: 120, align: 'right' },
  { label: '交易种类', prop: 'transType', width: 120 },
  { label: '业务日期', prop: 'bizDate', ...TIME_WIDTH_ATTRS },
  { label: '交易时间', prop: 'transTime', ...TIME_WIDTH_ATTRS },
  { label: '对方机构名称', prop: 'counterOrgName', width: 140 },
  { label: '对方账号', prop: 'counterAccountNo', width: 160 },
  { label: '客户号', prop: 'showCustomerId', width: 120 },
  { label: '客户名称', prop: 'customerName', width: 140 },
  { label: '结算金额', prop: 'settlementAmt', width: 120, align: 'right' },
  { label: '手续费', prop: 'feeAmt', width: 120, align: 'right' },
  { label: '代办人姓名', prop: 'agentName', width: 120 },
  { label: '备注', prop: 'comment', width: 140 },
]

export const nonBankCustomerColumns = [
  { label: '文件', prop: 'fileName', width: 100 },
  { label: '行号', prop: 'rowNum', width: 80, align: 'center' },
  { label: '机构名称', prop: 'orgName', width: 120 },
  { label: '商户号', prop: 'showMerchantId', width: 120 },
  { label: '商户名称', prop: 'merchantName', width: 140 },
  { label: '手机号码', prop: 'teleNum', width: 120 },
  { label: '店铺号', prop: 'portId', width: 100 },
  { label: '结算银行名称', prop: 'settlementOrg', width: 140 },
  { label: '结算账号/卡号', prop: 'settlementAccountNum', width: 160 },
  { label: '币种', prop: 'currNo', width: 90 },
  { label: '账户类型', prop: 'accountType', width: 100 },
  { label: '余额', prop: 'balence', width: 120, align: 'right' },
  { label: '客户种类', prop: 'customerType', width: 100 },
  { label: '营业执照', prop: 'licenseNum', width: 140 },
  { label: '法人姓名', prop: 'legalPersonName', width: 120 },
  { label: '商户证件种类', prop: 'idType', width: 120 },
  { label: '商户证件号码', prop: 'idNum', width: 140 },
  { label: '工作单位', prop: 'workUnit', width: 120 },
  { label: '备注', prop: 'comment', width: 140 },
]

export const nonBankTransactionColumns = [
  { label: '文件', prop: 'fileName', width: 100 },
  { label: '行号', prop: 'rowNum', width: 80, align: 'center' },
  { label: '机构名称', prop: 'orgName', width: 120 },
  { label: '商户号', prop: 'showMerchantId', width: 120 },
  { label: '商户名称', prop: 'merchantName', width: 140 },
  { label: '店铺号', prop: 'portId', width: 100 },
  { label: '订单号', prop: 'orderNo', width: 120 },
  { label: '商品名称', prop: 'productName', width: 140 },
  { label: '手机号码', prop: 'teleNum', width: 120 },
  { label: '流水号', prop: 'transNo', width: 120 },
  { label: '卡号', prop: 'cardNum', width: 140 },
  { label: '户名', prop: 'customerName', width: 120 },
  { label: '币种', prop: 'currNo', width: 90 },
  { label: '交易方向', prop: 'transWay', width: 100 },
  { label: '交易金额', prop: 'transAmt', width: 120, align: 'right' },
  { label: '贷方发生额', prop: 'creditAmt', width: 120, align: 'right' },
  { label: '交易种类', prop: 'transType', width: 110 },
  { label: '业务日期', prop: 'bizDate', ...TIME_WIDTH_ATTRS },
  { label: '交易时间', prop: 'transTime', ...TIME_WIDTH_ATTRS },
  { label: '交易卡开户行', prop: 'openOrgCd', width: 120 },
  { label: '客户号', prop: 'customerId', width: 120 },
  { label: '营业执照', prop: 'licenseNum', width: 140 },
  { label: '法人姓名', prop: 'legalPersonName', width: 120 },
  { label: '证件种类', prop: 'idType', width: 100 },
  { label: '证件号码', prop: 'idNum', width: 140 },
  { label: '结算金额', prop: 'settlementAmt', width: 120, align: 'right' },
  { label: '余额', prop: 'balance', width: 120, align: 'right' },
  { label: '备注', prop: 'comment', width: 140 },
]

export const intelligentDetailFields = [
  { label: '文件名称', prop: 'fileName' },
  { label: '行号', prop: 'rowNum' },
  { label: '机构名称', prop: 'orgName' },
  { label: '客户号', prop: 'customerCd' },
  { label: '客户名称', prop: 'customerName' },
  { label: '交易账号', prop: 'transAccountNo' },
  { label: '相关账号', prop: 'relAccountNo' },
  { label: '户名', prop: 'accountName' },
  { label: '币种', prop: 'currNo' },
  { label: '交易状态', prop: 'status' },
  { label: '交易方向', prop: 'transWay' },
  { label: '交易金额', prop: 'transAmt' },
  { label: '交易种类', prop: 'transType' },
  { label: '业务日期', prop: 'bizDate', ...TIME_WIDTH_ATTRS },
  { label: '交易时间', prop: 'transTime', ...TIME_WIDTH_ATTRS },
  { label: '余额', prop: 'balence' },
  { label: '对方机构名称', prop: 'counterOrgName' },
  { label: '对方账号', prop: 'counterAccountNo' },
  { label: '对方户名', prop: 'counterName' },
  { label: '流水号', prop: 'transNo' },
  { label: '交易渠道', prop: 'channel' },
  { label: '对方客户唯一识别', prop: 'counterCustomerId' },
  { label: '对方卡号', prop: 'counterCardNum' },
  { label: '交易对方证件号码', prop: 'counterIdNum' },
  { label: '交易对方证件种类', prop: 'counterIdType' },
  { label: '对方余额', prop: 'counterBalance' },
  { label: '来源', prop: 'sourceTable' },
  { label: '备注', prop: 'comment' },
  { label: '设备MAC', prop: 'macAddress' },
  { label: '交易IP地址', prop: 'ipAddress' },
  { label: '交易代码', prop: 'transCode' },
  { label: '结算金额', prop: 'settlementAmt' },
  { label: '手续费', prop: 'feeAmt' },
  { label: '利息', prop: 'interestAmt' },
  { label: '违约金', prop: 'liquidatedAmt' },
  { label: '交易柜员', prop: 'teller' },
  { label: '交易发生地', prop: 'transLocation' },
  { label: '服务界面', prop: 'serviceInterface' },
  { label: '凭证号', prop: 'bankPaperNum' },
  { label: '凭证种类', prop: 'bankPaperType' },
  { label: '现金标志', prop: 'cashStatus' },
  { label: '钞汇标志', prop: 'fxCashStatus' },
  { label: '交易渠道代码', prop: 'transChannelCd' },
  { label: '终端号', prop: 'portNumber' },
  { label: '代办人姓名', prop: 'agentName' },
  { label: '代办人电话', prop: 'agentTel' },
  { label: '代办人证件号码', prop: 'agentIdNum' },
  { label: '代办人证件类型', prop: 'adengIdType' },
]

export const sourceTabLabelMap = {
  bankCustomerPageList: '银行客户信息',
  bankTransPageList: '银行交易流水',
  nonBankCustomerPageList: '非银行客户信息',
  nonBankTransPageList: '非银行交易流水',
} as const

export const sourceColumnsMap = {
  bankCustomerPageList: bankCustomerColumns,
  bankTransPageList: bankTransactionColumns,
  nonBankCustomerPageList: nonBankCustomerColumns,
  nonBankTransPageList: nonBankTransactionColumns,
}

export const sourceDetailFieldMap = {
  bankCustomerPageList: [
    ...bankCustomerColumns.map((item) => ({ label: item.label, prop: item.prop })),
    { label: '地税纳税号', prop: 'localTaxNum' },
    { label: '国税纳税号', prop: 'countryTaxNum' },
    { label: '法人证件种类', prop: 'legalIdType' },
    { label: '法人证件号码', prop: 'legalIdNum' },
    { label: '住宅电话', prop: 'homeTel' },
    { label: '单位电话', prop: 'unitTel' },
    { label: '状态', prop: 'customerStatus' },
    { label: '开户日期', prop: 'openDate' },
    { label: '可用余额', prop: 'avaiBalence' },
    { label: '开户网点', prop: 'openBranches' },
    { label: '开户网点代码', prop: 'openBranchesCd' },
    { label: '开户城市', prop: 'openCity' },
    { label: '开户省份', prop: 'openProvince' },
    { label: '关联资金账户', prop: 'cashAccountRel' },
    { label: '统一客户号', prop: 'customerCd' },
    { label: '清洗规则', prop: 'cleanRule' },
    { label: '通信地址', prop: 'communicationAddr' },
    { label: '住宅地址', prop: 'homeAddr' },
    { label: '单位地址', prop: 'unitAddr' },
    { label: '邮箱地址', prop: 'mailAddr' },
    { label: '邮政编码', prop: 'postCode' },
    { label: '销户日期', prop: 'closeDate' },
    { label: '销户网点', prop: 'closeBranches' },
    { label: '最后交易时间', prop: 'lastTransTime' },
    { label: '账户销户银行', prop: 'closeBank' },
  ],
  bankTransPageList: [
    ...bankTransactionColumns.map((item) => ({ label: item.label, prop: item.prop })),
    { label: '利息', prop: 'interestAmt' },
    { label: '违约金', prop: 'liquidatedAmt' },
    { label: '设备MAC', prop: 'macAddress' },
    { label: '交易IP地址', prop: 'ipAddress' },
    { label: '交易状态', prop: 'status' },
    { label: '对方客户唯一识别', prop: 'counterCustomerId' },
    { label: '对方机构编码', prop: 'counterOrgCd' },
    { label: '对方卡号', prop: 'counterCardNum' },
    { label: '交易对方证件号码', prop: 'counterIdNum' },
    { label: '交易对方余额', prop: 'counterBalance' },
    { label: '统一客户号', prop: 'customerCd' },
    { label: '客户种类', prop: 'customerType' },
    { label: '营业执照', prop: 'licenseNum' },
    { label: '法人姓名', prop: 'legalPersonName' },
    { label: '证件种类', prop: 'idType' },
    { label: '证件号码', prop: 'idNum' },
    { label: '手机号码', prop: 'teleNum' },
    { label: '清洗规则', prop: 'cleanRule' },
    { label: '交易代码', prop: 'transCode' },
    { label: '交易柜员', prop: 'teller' },
    { label: '交易发生地', prop: 'transLocation' },
    { label: '服务界面', prop: 'serviceInterface' },
    { label: '凭证号', prop: 'bankPaperNum' },
    { label: '凭证种类', prop: 'bankPaperType' },
    { label: '现金标志', prop: 'cashStatus' },
    { label: '钞汇标志', prop: 'fxCashStatus' },
    { label: '交易渠道', prop: 'transChannel' },
    { label: '交易渠道代码', prop: 'transChannelCd' },
    { label: '终端号', prop: 'portNumber' },
    { label: '代办人电话', prop: 'agentTel' },
    { label: '代办人证件号码', prop: 'agentIdNum' },
    { label: '代办人证件类型', prop: 'adengIdType' },
  ],
  nonBankCustomerPageList: [
    ...nonBankCustomerColumns.map((item) => ({ label: item.label, prop: item.prop })),
    { label: '是否商户', prop: 'isMerchant' },
    { label: '结算银行编码', prop: 'settlementOrgCd' },
    { label: '账户状态', prop: 'accontStatus' },
    { label: '开户日期', prop: 'openDate' },
    { label: '可用余额', prop: 'avaiBalence' },
    { label: '地税纳税号', prop: 'localTaxNum' },
    { label: '国税纳税号', prop: 'countryTaxNum' },
    { label: '法人证件种类', prop: 'legalIdType' },
    { label: '法人证件号码', prop: 'legalIdNum' },
    { label: '住宅电话', prop: 'homeTel' },
    { label: '单位电话', prop: 'unitTel' },
    { label: '状态', prop: 'customerStatus' },
    { label: '客户号', prop: 'customerId' },
    { label: '客户名称', prop: 'customerName' },
    { label: '统一客户号', prop: 'customerCd' },
    { label: '清洗规则', prop: 'cleanRule' },
    { label: '通信地址', prop: 'communicationAddr' },
    { label: '住宅地址', prop: 'homeAddr' },
    { label: '单位地址', prop: 'unitAddr' },
    { label: '邮箱地址', prop: 'mailAddr' },
    { label: '邮政编码', prop: 'postCode' },
    { label: '开户网点', prop: 'openBranches' },
    { label: '开户网点代码', prop: 'openBranchesCd' },
    { label: '销户日期', prop: 'closeDate' },
    { label: '最后交易时间', prop: 'lastTransTime' },
  ],
  nonBankTransPageList: [
    ...nonBankTransactionColumns.map((item) => ({ label: item.label, prop: item.prop })),
    { label: '客户种类', prop: 'customerType' },
    { label: '结算行', prop: 'settlementOrg' },
    { label: '结算行编码', prop: 'settlementOrgCd' },
    { label: '结算账号', prop: 'settlementAccountNum' },
    { label: '卡类型', prop: 'cardType' },
    { label: '设备MAC', prop: 'macAddress' },
    { label: '交易IP地址', prop: 'ipAddress' },
    { label: '交易状态', prop: 'status' },
    { label: '统一客户号', prop: 'customerCd' },
    { label: '清洗规则', prop: 'cleanRule' },
    { label: '交易渠道', prop: 'transChannel' },
    { label: '交易代码', prop: 'transCode' },
    { label: '手续费', prop: 'feeAmt' },
    { label: '现金标志', prop: 'cashStatus' },
    { label: '钞汇标志', prop: 'fxCashStatus' },
    { label: '交易发生地', prop: 'transLocation' },
  ],
}
